/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as RenterRouteImport } from './routes/renter'
import { Route as PropertyClassifyRouteImport } from './routes/property-classify'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as DamageEvalRouteImport } from './routes/damage-eval'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const RenterRoute = RenterRouteImport.update({
  id: '/renter',
  path: '/renter',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyClassifyRoute = PropertyClassifyRouteImport.update({
  id: '/property-classify',
  path: '/property-classify',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const DamageEvalRoute = DamageEvalRouteImport.update({
  id: '/damage-eval',
  path: '/damage-eval',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/damage-eval': typeof DamageEvalRoute
  '/owner': typeof OwnerRoute
  '/property-classify': typeof PropertyClassifyRoute
  '/renter': typeof RenterRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/damage-eval': typeof DamageEvalRoute
  '/owner': typeof OwnerRoute
  '/property-classify': typeof PropertyClassifyRoute
  '/renter': typeof RenterRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/damage-eval': typeof DamageEvalRoute
  '/owner': typeof OwnerRoute
  '/property-classify': typeof PropertyClassifyRoute
  '/renter': typeof RenterRoute
  '/thank-you': typeof ThankYouRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/damage-eval'
    | '/owner'
    | '/property-classify'
    | '/renter'
    | '/thank-you'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/damage-eval'
    | '/owner'
    | '/property-classify'
    | '/renter'
    | '/thank-you'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/damage-eval'
    | '/owner'
    | '/property-classify'
    | '/renter'
    | '/thank-you'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DamageEvalRoute: typeof DamageEvalRoute
  OwnerRoute: typeof OwnerRoute
  PropertyClassifyRoute: typeof PropertyClassifyRoute
  RenterRoute: typeof RenterRoute
  ThankYouRoute: typeof ThankYouRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renter': {
      id: '/renter'
      path: '/renter'
      fullPath: '/renter'
      preLoaderRoute: typeof RenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-classify': {
      id: '/property-classify'
      path: '/property-classify'
      fullPath: '/property-classify'
      preLoaderRoute: typeof PropertyClassifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/damage-eval': {
      id: '/damage-eval'
      path: '/damage-eval'
      fullPath: '/damage-eval'
      preLoaderRoute: typeof DamageEvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DamageEvalRoute: DamageEvalRoute,
  OwnerRoute: OwnerRoute,
  PropertyClassifyRoute: PropertyClassifyRoute,
  RenterRoute: RenterRoute,
  ThankYouRoute: ThankYouRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
